### PR TITLE
Added cookiejar object to store multiple cookies comfortably

### PR DESCRIPTION
**Pull request by dgrr**
Also I changed and adapted the examples to the new API. Fixing https://github.com/erikdubbelboer/fasthttp/pull/37

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
I'm not sure if it's a good idea to add so much extra code for something that can already be done using the currently available functions.

**Comment by dgrr** [comment]
I can add it in another package (fasthttp/cookiejar) if you want.

**Comment by erikdubbelboer** [comment]
That would still add extra code that isn't really needed but will need to be maintained in the future.

**Comment by thehowl** [comment]
I agree. I don't think we need to provide cookiejar functionality. If anything anyone who wants to do a more higher-level framework can provide this.

**Comment by dgrr** [comment]
https://github.com/themester/fcookiejar

**Pull request closed without merging**
