### PR TITLE
Add method to get cookie from response

### PR DESCRIPTION
**Pull request by tianxiaoliang**
M developing a proxy which has session stickiness strategy, So I write a convinience API

### CODE REVIEW

**Comment by dgrr** [comment]
Thanks. Can you call Cookie() instead of GetCookie() as RequestHeader function?  (https://godoc.org/github.com/erikdubbelboer/fasthttp#RequestHeader.Cookie)

**Comment by erikdubbelboer** [comment]
He's taking about the ResponseHeader so that would be https://godoc.org/github.com/erikdubbelboer/fasthttp#ResponseHeader.Cookie

The difference is that this method actually parses the cookie into a https://godoc.org/github.com/erikdubbelboer/fasthttp#Cookie

I guess for people that want fast access without parsing the whole cookie a method like this could be useful. But I think it's better to call it `PeekCookie`.

**Comment by tianxiaoliang** [comment]
it can not be named as Cookie, and PeekCookie is great

**Comment by dgrr** [comment]
Sorry. I didn't see the Cookie method in ResponseHeader

**Comment by erikdubbelboer** [comment]
Thanks.

**Comment by tianxiaoliang** [comment]
if M wrong,plz correct me, ResponseHeader and ReqeustHeader is just reciever, and func Cookie(h *ResponseHeader, key string) is equal to func (h *ResponseHeader) Cookie( key string), which means  Cookie(h *ResponseHeader, key string) and Cookie(h *RequestHeader, key string) use the same func name. How should I do?

**Comment by erikdubbelboer** [comment]
No they are implement differently. [`ResponseHeader.Cookie()`](https://godoc.org/github.com/erikdubbelboer/fasthttp#ResponseHeader.Cookie) uses the [`Cookie`](https://godoc.org/github.com/erikdubbelboer/fasthttp#Cookie) struct while [`RequestHeader.Cookie()`](https://godoc.org/github.com/erikdubbelboer/fasthttp#RequestHeader.Cookie) only works with strings or bytes.

The reason for this is that an HTTP request only contains a `Cookie: name=value` while an HTTP response contains `Set-Cookie: name=value; Expires=... ; Path=...; etc...` with all kinds of options. That's why [`ResponseHeader.Cookie()`](https://godoc.org/github.com/erikdubbelboer/fasthttp#ResponseHeader.Cookie) uses the [`Cookie`](https://godoc.org/github.com/erikdubbelboer/fasthttp#Cookie) struct to put those options in.

**Pull request merged**
