### PR TITLE
Added Writer in client and tlsConfig in server.

### PR DESCRIPTION
**Pull request by dgrr**
Writer io.Writer have been added to Client structure to allow programmer download files directly without storing in memory.
tlsConfig *tls.Conifg have been added to Server structure to allow programmer handle multiple domains with multiple certificates.

### CODE REVIEW

**Comment by illotum** [comment]
I feel like all TLS shenanigans are misguided here. It is so much easier to

```go
tlsC := &tls.Config{
	Certificates: certs,
}
tlsC.BuildNameToCertificate() // I also think you forgot this.

ln := tls.NewListener(tcpLn, tlsC) // same can be done using valyala/tcplisten
srv.Serve(ln)
```
In general I feel we should try to reduce lib's API, not increase. All kinds of convenience methods are niche at best and confusing at worst.

**Comment by dgrr** [comment]
@illotum well seen. I done it hurry to solve a problem on a http server.

**Comment by erikdubbelboer** [comment]
@themester this is too many big changes for one pull request. Can you please put the TLS stuff in a different pull request.

You alsoreally need to rebase on master so that first two comments aren't in here. They make it impossible to see what actually changes in the diff.

Your `Response.copyBody` method also still only works for bodies with a `Content-Length` header. Chunked encoding will return the encoded body instead of decoding it like it should.

You should also add some documentation on what happens with gzipped bodies. Normally someone would use [Response.BodyGunzip()](https://godoc.org/github.com/valyala/fasthttp#Response.BodyGunzip) but with your `Writer` they would have to handle this themselves for example using a [io.Pipe](https://golang.org/pkg/io/#Pipe) into a [gzip.Reader](https://golang.org/pkg/compress/gzip/#NewReader).

**Comment by dgrr** [comment]
@erikdubbelboer okay. The next week I will start doing changes on my repo. I busy this week. Sorry for the inconveniences.

**Pull request closed without merging**
